services:
  frontend:
    build : ./client 
    image: student-repo-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    networks:
      - student-repo-network
    
  backend1:
    build : ./server
    image: student-repo-server
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - SECRET_KEY=mykey123
      - MONGODBURL=mongodb://root:root@mongodb:27017/?authSource=admin
    networks:
      - student-repo-network
  backend2:
    build : ./server
    image: student-repo-server
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - SECRET_KEY=mykey123
      - MONGODBURL=mongodb://root:root@mongodb:27017/?authSource=admin
    networks:
      - student-repo-network
  backend3:
    build : ./server
    image: student-repo-server
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - SECRET_KEY=mykey123
      - MONGODBURL=mongodb://root:root@mongodb:27017/?authSource=admin
    networks:
      - student-repo-network
  backend4:
    build : ./server
    image: student-repo-server
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - SECRET_KEY=mykey123
      - MONGODBURL=mongodb://root:root@mongodb:27017/?authSource=admin
    networks:
      - student-repo-network
    
  mongodb:
    image : mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - student-repo-network
    volumes:
      - mongo-data:/data/db

networks:
  student-repo-network:
    driver: bridge

volumes:
  mongo-data: