apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 4

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: samyak2005/scr-server:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SECRET_KEY

            - name: MONGODBURL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGODBURL